### ISSUE TITLE
Reconciling with cjdk and/or jvm-index

### ISSUE THREAD

**Issue by ctrueden** [jyksnw/install-jdk#143]
Hello! :wave: I'm an author of [jgo](https://github.com/scijava/jgo), and my colleague @marktsuchida is the author of [cjdk](https://github.com/cachedjdk/cjdk). The cjdk project fills a very similar need to install-jdk, providing a command-line tool written in Python for downloading and caching JDKs. It uses [jvm-index](https://github.com/coursier/jvm-index) from the Coursier project as its source of truth for which JVM implementations are available from where, which makes things a bit easier.

For a while now, we have been scheming—when we have some spare time, which of course no one ever has...—to make cjdk a dependency of jgo, such that jgo can not only launch Java code from remote Maven repositories from the CLI, but also do so without a JDK/JRE already being present and available. However, since cjdk was written, we noticed that install-jdk has been actively developed for the past few months.

Therefore, I'm reaching out to get your thoughts on how—if at all—all of these projects might work together for the betterment of the community.
* Were you already aware of cjdk? If so, how do you see the respective niches of install-jdk vs cjdk? Or if not, do you think it would make sense to join forces and share/consolidate any code?
* Did you already know about the jvm-index? Maybe using it could help install-jdk to save some code in its implementation?
* If cjdk and install-jdk could be combined into a single project meeting all requirements, that would be awesome. But if not, what do you think might be the best way forward for jgo to integrate some JDK-downloading functionality? Should I just pick one of cjdk or install-jdk, or might there be reasons to bake in both as options?

Looking forward to reading your thoughts! :smile:

**Comment by jyksnw** [comment]
Thanks for the question and inquiry.

install-jdk is already used in many large projects due to its ease of use, multiple vendor support, and predictable installation. Many companies already depend on install-jdk for predictable and OpenJDK-compliant installations. Because of this, I am hesitant to make any API changes or introduce vastly different paradigms.

I would be interested to know what particular aspects of cjdk you feel install-jdk could benefit from.

With regard to jvm-index; I believe the approach that install-jdk uses with regard to going directly to the vendor API has many benefits and allows for greater flexibility for anyone using install-jdk to take full advantage of individual vendor implementation details. This does have some added complexity in terms of maintenance against various vendor API but I believe the effort is worth the benefits.
